---
kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world

trigger:
  event:
    exclude:
      - promote
      - rollback
