---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy
    commands:
      - docker build -t taylorivanoff .
      - docker images --filter reference=taylorivanoff
