---
kind: pipeline
type: ssh
name: default

server:
  host: localhost
  user: taylor
  password:
    from_secret: ssh_password

steps:
  - name: deploy
    commands:
      - docker build . -t taylorivanoff
      - docker images --filter reference=taylorivanoff
