---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare
    commands:
      - docker kill "taylorivanoff-nginx" "taylorivanoff-app"
      - docker rm "taylorivanoff-nginx" "taylorivanoff-app"
      - rm -Rf "/home/taylor/sites/taylorivanoff.com"
      - mkdir -p "/home/taylor/sites/taylorivanoff.com"
      - cp -R . "/home/taylor/sites/taylorivanoff.com"
      - cd "/home/taylor/sites/taylorivanoff.com"
      - pwd
      - ls -la
