---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy
    commands:
      - docker kill "taylorivanoff-nginx" "taylorivanoff-app" || true
      - docker rm "taylorivanoff-nginx" "taylorivanoff-app" || true
      - rm -Rf "/home/taylor/sites/taylorivanoff.com"
      - mkdir -p "/home/taylor/sites/taylorivanoff.com"
      - cp -R . "/home/taylor/sites/taylorivanoff.com"
      - cd "/home/taylor/sites/taylorivanoff.com"
      - composer install
      - pwd
      - ls -la
      - docker compose build app
      - docker compose up -d
