---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: greeting
    commands:
      - docker compose build app
      - docker compose down
      - docker compose up -d
