---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare
    commands:
      - docker kill "taylorivanoff-nginx" "taylorivanoff-app" || true
      - docker rm "taylorivanoff-nginx" "taylorivanoff-app" || true
      - cd /home/taylor/sites/
#      - rm -Rf "/home/taylor/sites/taylorivanoff.com" || true
#      - mkdir -p

