---
kind: pipeline
type: ssh
name: default

server:
  host: 149.28.167.163
  user: taylor
  password:
    from_secret: ssh_password

steps:
  - name: deploy
    commands:
      - cp -R . "/home/taylor/sites/${DRONE_REPO_NAME}"
      - cd "/home/taylor/sites/${DRONE_REPO_NAME}"
      - docker compose up -d --force-recreate --remove-orphans
