pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose -f ./deploy/docker-compose.yml build
      - docker compose -f ./deploy/docker-compose.yml up --no-deps -d
