# Define the language and version for your project
language: php
version: 8

# Specify the steps for your build and deployment
build:
  script:
    - composer install
    - php artisan migrate --seed

deploy:
  script:
    - rsync -avz --delete-after --exclude-from=.deployignore . /home/sites/${CI_REPO_NAME}


