pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose -f docker-compose.prod.yml build
      - docker compose -f docker-compose.prod.yml up --no-deps -d

