pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose build app

  start:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose down
      - docker compose up -d --remove-orphans

  install:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose exec app ls -l
      - docker compose exec app rm -rf vendor composer.lock
      - docker compose exec app composer install
#      - docker compose exec php artisan key:generate

