steps:
  build:
    image: debian
    commands:
      - rsync -avz --delete-after --exclude-from=.deployignore . /home/sites/${CI_REPO_NAME}

#  build:
#    image: docker
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    commands:
#      - docker compose -f docker-compose.prod.yml build
#      - docker compose -f docker-compose.prod.yml up --no-deps -d
