pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - /bin/sh deploy/build.sh
      - cd deploy || return
      - docker compose exec app composer install
      - cp .env.example .env
