pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t taylorivanoff .
      - docker compose up -d --remove-orphans
