services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: sammy
        uid: 1000
    image: taylorivanoff
    container_name: taylorivanoff-app
    restart: always
    working_dir: /home/sammy
    volumes:
      - ./:/home/sammy
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: taylorivanoff-nginx
    restart: always
    volumes:
      - ./:/home/sammy
      - ./deploy/nginx:/etc/nginx/conf.d/
    networks:
      - default
      - proxy-network

networks:
  default:
  proxy-network:
    external: true
