version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: taylorivanoff
    container_name: taylorivanoff-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - taylor-network

  nginx:
    image: nginx:alpine
    container_name: taylorivanoff-nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - taylor-network

networks:
  taylor-network:
    external: true
