version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: taylorivanoff
    container_name: taylorivanoff-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - taylorivanoff

  nginx:
    image: nginx:alpine
    container_name: taylorivanoff-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./deploy/nginx:/etc/nginx/conf.d/
    networks:
      - taylorivanoff
      - proxy-network

networks:
  taylorivanoff:
  proxy-network:
    external: true
