version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: taylor
        uid: 1000
    image: taylorivanoff
    container_name: taylorivanoff-app
    restart: always
    working_dir: /var/www/
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./:/var/www
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: taylorivanoff-nginx
    restart: always
    volumes:
      - ./:/var/www
      - ./deploy/nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"    # Map host port 80 to container port 80
      - "443:443"  # Map host port 443 to container port 443
    networks:
      - default
      - proxy-network

networks:
  default:
  proxy-network:
    external: true
