version: '3.8'

services:
  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - php-fpm

networks:
  app-network:
    driver: bridge
