version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: sammy
        uid: 1000
    image: taylorivanoff
    container_name: taylorivanoff-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: taylorivanoff-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./deploy/nginx:/etc/nginx/conf.d/
