services:
  app:
    restart: always
    networks:
      - default

  nginx:
    restart: always
    networks:
      - default
      - proxy-network

networks:
  default:
  proxy-network:
    external: true
