version: '3'
services:
  app:
    build:
      context: ./
    container_name: taylorivanoff
    volumes:
      - .:/var/www/html
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
