version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: taylorivanoff
    container_name: taylorivanoff-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - nginx-reverse-proxy

  nginx:
    image: nginx:alpine
    container_name: taylorivanoff-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nginx-reverse-proxy
    environment:
      VIRTUAL_HOST: taylorivanoff.com
      LETSENCRYPT_HOST: taylorivanoff.com

networks:
  nginx-reverse-proxy:
    external: true
